# Generated by Django 4.1.5 on 2023-01-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='email_subscription',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to='profile-imgs'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='sms_notification',
            field=models.BooleanField(default=True),
        ),
    ]
